version: '3'
services:
  db:
    image: postgres:9.6-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data\
    ports:
      - 5432:5432
    container_name: pgsql
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test


volumes:
  postgres-data: